# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  name: Default

variables:
  - name: VITE_API_URL
    value: "https://bespoked-bikes-service-g0bea9c6adgfhcb9.centralus-01.azurewebsites.net/api"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      cd client
      npm install
      npm run build
    displayName: "npm install and build"

  - task: CopyFiles@2
    inputs:
      Contents: "client/dist/**"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
    displayName: "Copy build files"

  - task: AzureStaticWebApp@0
    inputs:
      app_location: "client/dist"
      api_location: ""
      output_location: ""
      deployment_token: $(DEPLOYMENT_TOKEN)
    displayName: "Deploy to Azure Static Web App"
