trigger:
  - master

pool:
  name: Default

variables:
  - name: api_app_name
    value: "bespoked-bikes-service"
  - name: API_URL
    value: "https://$(api_app_name).azurewebsites.net/api"
  - name: RESOURCE_GROUP
    value: "Profisee"

jobs:
  - job: BuildAndDeployAPI
    strategy:
      matrix:
        api:
          name: api
          project: server/server.csproj
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: "build"
          projects: $(project)
      - task: DotNetCoreCLI@2
        inputs:
          command: "publish"
          publishWebProjects: true
          arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)"
      - task: AzureWebApp@1
        inputs:
          azureSubscription: "Profisee Service Connection"
          appName: "$(api_app_name)"
          package: "$(Build.ArtifactStagingDirectory)/**/*.zip"
      - task: AzureCLI@2
        inputs:
          azureSubscription: "Profisee Service Connection"
          scriptType: "ps"
          scriptLocation: "inlineScript"
          inlineScript: |
            az webapp config appsettings set `
              --name $(api_app_name) `
              --resource-group $(RESOURCE_GROUP) `
              --settings `
                WEBSITE_RUN_FROM_PACKAGE=1 `
                PORT=80 `
                ASPNETCORE_ENVIRONMENT=Production `
                DB_CONNECTION_STRING="$(DB_CONNECTION_STRING)" `
                JWT_SECRET="$(JWT_SECRET)" `
                CORS_ORIGINS="https://bespoked-bikes.azurestaticapps.net" `
                LOG_LEVEL=Information

  - job: BuildAndDeployWeb
    dependsOn: BuildAndDeployAPI
    strategy:
      matrix:
        web:
          name: web
          workingDir: client
    variables:
      VITE_API_URL: $[variables.API_URL]
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"
      - task: Npm@1
        inputs:
          command: "install"
          workingDir: $(workingDir)
      - task: Npm@1
        inputs:
          command: "custom"
          workingDir: $(workingDir)
          customCommand: "run build"
        env:
          VITE_API_URL: $(VITE_API_URL)
          VITE_ENABLE_MOCK_DATA: "false"
      - task: AzureStaticWebApp@0
        inputs:
          app_location: "$(workingDir)/dist"
          azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
          skip_app_build: true
