// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250315210039_AddMoreMockData")]
    partial class AddMoreMockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("server.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "234 Elm St, Seattle, WA 98104",
                            FirstName = "Robert",
                            LastName = "Anderson",
                            Phone = "206-555-4567",
                            StartDate = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "567 Cedar Ln, Seattle, WA 98105",
                            FirstName = "Jennifer",
                            LastName = "Wilson",
                            Phone = "206-555-5678",
                            StartDate = new DateTime(2020, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "890 Maple Dr, Seattle, WA 98106",
                            FirstName = "David",
                            LastName = "Thompson",
                            Phone = "206-555-6789",
                            StartDate = new DateTime(2021, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 Oak St, Seattle, WA 98107",
                            FirstName = "Lisa",
                            LastName = "Martinez",
                            Phone = "206-555-7890",
                            StartDate = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "456 Pine Ln, Seattle, WA 98108",
                            FirstName = "Michael",
                            LastName = "Brown",
                            Phone = "206-555-8901",
                            StartDate = new DateTime(2021, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "789 Cedar Ave, Seattle, WA 98109",
                            FirstName = "Sarah",
                            LastName = "Davis",
                            Phone = "206-555-9012",
                            StartDate = new DateTime(2020, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "321 Birch Rd, Seattle, WA 98110",
                            FirstName = "Daniel",
                            LastName = "Taylor",
                            Phone = "206-555-0123",
                            StartDate = new DateTime(2022, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "654 Maple St, Seattle, WA 98111",
                            FirstName = "Amanda",
                            LastName = "Johnson",
                            Phone = "206-555-1234",
                            StartDate = new DateTime(2021, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "987 Elm Dr, Seattle, WA 98112",
                            FirstName = "Christopher",
                            LastName = "Miller",
                            Phone = "206-555-2345",
                            StartDate = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "159 Spruce Ave, Seattle, WA 98113",
                            FirstName = "Jessica",
                            LastName = "Williams",
                            Phone = "206-555-3456",
                            StartDate = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Address = "357 Cedar Ln, Seattle, WA 98114",
                            FirstName = "Matthew",
                            LastName = "Jones",
                            Phone = "206-555-4567",
                            StartDate = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Address = "852 Pine St, Seattle, WA 98115",
                            FirstName = "Emily",
                            LastName = "Garcia",
                            Phone = "206-555-5678",
                            StartDate = new DateTime(2020, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Address = "953 Oak Dr, Seattle, WA 98116",
                            FirstName = "Joshua",
                            LastName = "Smith",
                            Phone = "206-555-6789",
                            StartDate = new DateTime(2021, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Address = "147 Maple Rd, Seattle, WA 98117",
                            FirstName = "Ashley",
                            LastName = "Rodriguez",
                            Phone = "206-555-7890",
                            StartDate = new DateTime(2022, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Address = "258 Elm Ave, Seattle, WA 98118",
                            FirstName = "Andrew",
                            LastName = "Martinez",
                            Phone = "206-555-8901",
                            StartDate = new DateTime(2021, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Address = "369 Birch St, Seattle, WA 98119",
                            FirstName = "Nicole",
                            LastName = "Hernandez",
                            Phone = "206-555-9012",
                            StartDate = new DateTime(2020, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Address = "741 Cedar Dr, Seattle, WA 98120",
                            FirstName = "William",
                            LastName = "Moore",
                            Phone = "206-555-0123",
                            StartDate = new DateTime(2022, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Address = "852 Pine Ln, Seattle, WA 98121",
                            FirstName = "Stephanie",
                            LastName = "Martin",
                            Phone = "206-555-1234",
                            StartDate = new DateTime(2021, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Address = "963 Oak Ave, Seattle, WA 98122",
                            FirstName = "Joseph",
                            LastName = "Jackson",
                            Phone = "206-555-2345",
                            StartDate = new DateTime(2020, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Address = "159 Maple St, Seattle, WA 98123",
                            FirstName = "Elizabeth",
                            LastName = "Thompson",
                            Phone = "206-555-3456",
                            StartDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Address = "357 Elm Rd, Seattle, WA 98124",
                            FirstName = "Ryan",
                            LastName = "White",
                            Phone = "206-555-4567",
                            StartDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Address = "753 Birch Ave, Seattle, WA 98125",
                            FirstName = "Megan",
                            LastName = "Lopez",
                            Phone = "206-555-5678",
                            StartDate = new DateTime(2020, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Address = "951 Cedar St, Seattle, WA 98126",
                            FirstName = "Kevin",
                            LastName = "Lee",
                            Phone = "206-555-6789",
                            StartDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Address = "147 Pine Dr, Seattle, WA 98127",
                            FirstName = "Rachel",
                            LastName = "Gonzalez",
                            Phone = "206-555-7890",
                            StartDate = new DateTime(2021, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Address = "258 Oak Ln, Seattle, WA 98128",
                            FirstName = "Brian",
                            LastName = "Nelson",
                            Phone = "206-555-8901",
                            StartDate = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Address = "369 Maple Ave, Seattle, WA 98129",
                            FirstName = "Lauren",
                            LastName = "Hill",
                            Phone = "206-555-9012",
                            StartDate = new DateTime(2022, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Address = "741 Elm St, Seattle, WA 98130",
                            FirstName = "Justin",
                            LastName = "Ramirez",
                            Phone = "206-555-0123",
                            StartDate = new DateTime(2021, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Address = "852 Birch Rd, Seattle, WA 98131",
                            FirstName = "Samantha",
                            LastName = "Campbell",
                            Phone = "206-555-1234",
                            StartDate = new DateTime(2020, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Address = "963 Cedar Ave, Seattle, WA 98132",
                            FirstName = "Brandon",
                            LastName = "Baker",
                            Phone = "206-555-2345",
                            StartDate = new DateTime(2022, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Address = "159 Pine St, Seattle, WA 98133",
                            FirstName = "Melissa",
                            LastName = "Rivera",
                            Phone = "206-555-3456",
                            StartDate = new DateTime(2021, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("server.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 15.0m,
                            EndDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeginDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 10.0m,
                            EndDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            BeginDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 12.5m,
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            BeginDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 8.0m,
                            EndDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            BeginDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 20.0m,
                            EndDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            BeginDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 15.0m,
                            EndDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            BeginDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 25.0m,
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            BeginDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 10.0m,
                            EndDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            BeginDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 12.0m,
                            EndDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            BeginDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 18.0m,
                            EndDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            BeginDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 15.0m,
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            BeginDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 12.5m,
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            BeginDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 20.0m,
                            EndDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            BeginDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 10.0m,
                            EndDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            BeginDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscountPercentage = 15.0m,
                            EndDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 15
                        });
                });

            modelBuilder.Entity("server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionPercentage = 10.5m,
                            Manufacturer = "Trek",
                            Name = "Mountain Explorer 5000",
                            PurchasePrice = 899.99m,
                            QuantityOnHand = 10,
                            SalePrice = 1499.99m,
                            Style = "Mountain"
                        },
                        new
                        {
                            Id = 2,
                            CommissionPercentage = 12.0m,
                            Manufacturer = "Specialized",
                            Name = "Road Master Elite",
                            PurchasePrice = 1200m,
                            QuantityOnHand = 7,
                            SalePrice = 2199.99m,
                            Style = "Road"
                        },
                        new
                        {
                            Id = 3,
                            CommissionPercentage = 8.5m,
                            Manufacturer = "Giant",
                            Name = "City Cruiser Deluxe",
                            PurchasePrice = 750m,
                            QuantityOnHand = 15,
                            SalePrice = 1299.99m,
                            Style = "Urban"
                        },
                        new
                        {
                            Id = 4,
                            CommissionPercentage = 9.0m,
                            Manufacturer = "Cannondale",
                            Name = "Hybrid Sport 700C",
                            PurchasePrice = 850m,
                            QuantityOnHand = 12,
                            SalePrice = 1399.99m,
                            Style = "Hybrid"
                        },
                        new
                        {
                            Id = 5,
                            CommissionPercentage = 11.0m,
                            Manufacturer = "Rad Power Bikes",
                            Name = "Electric City Pro",
                            PurchasePrice = 1200m,
                            QuantityOnHand = 8,
                            SalePrice = 1999.99m,
                            Style = "Electric"
                        },
                        new
                        {
                            Id = 6,
                            CommissionPercentage = 13.5m,
                            Manufacturer = "Santa Cruz",
                            Name = "Mountain Trail X2",
                            PurchasePrice = 1500m,
                            QuantityOnHand = 5,
                            SalePrice = 2499.99m,
                            Style = "Mountain"
                        },
                        new
                        {
                            Id = 7,
                            CommissionPercentage = 15.0m,
                            Manufacturer = "Cervélo",
                            Name = "Speed Demon Racing",
                            PurchasePrice = 2000m,
                            QuantityOnHand = 3,
                            SalePrice = 3599.99m,
                            Style = "Road"
                        },
                        new
                        {
                            Id = 8,
                            CommissionPercentage = 7.5m,
                            Manufacturer = "Electra",
                            Name = "Comfort Cruiser Plus",
                            PurchasePrice = 600m,
                            QuantityOnHand = 20,
                            SalePrice = 999.99m,
                            Style = "Cruiser"
                        },
                        new
                        {
                            Id = 9,
                            CommissionPercentage = 8.0m,
                            Manufacturer = "Trek",
                            Name = "Urban Commuter X3",
                            PurchasePrice = 700m,
                            QuantityOnHand = 14,
                            SalePrice = 1199.99m,
                            Style = "Urban"
                        },
                        new
                        {
                            Id = 10,
                            CommissionPercentage = 11.5m,
                            Manufacturer = "Specialized",
                            Name = "Trail Blazer Pro",
                            PurchasePrice = 1100m,
                            QuantityOnHand = 6,
                            SalePrice = 1899.99m,
                            Style = "Mountain"
                        },
                        new
                        {
                            Id = 11,
                            CommissionPercentage = 10.0m,
                            Manufacturer = "Brompton",
                            Name = "Folding City Bike",
                            PurchasePrice = 950m,
                            QuantityOnHand = 9,
                            SalePrice = 1599.99m,
                            Style = "Folding"
                        },
                        new
                        {
                            Id = 12,
                            CommissionPercentage = 12.5m,
                            Manufacturer = "Salsa",
                            Name = "Gravel Adventure X1",
                            PurchasePrice = 1300m,
                            QuantityOnHand = 7,
                            SalePrice = 2299.99m,
                            Style = "Gravel"
                        },
                        new
                        {
                            Id = 13,
                            CommissionPercentage = 6.0m,
                            Manufacturer = "Giant",
                            Name = "Kids Explorer 24",
                            PurchasePrice = 300m,
                            QuantityOnHand = 25,
                            SalePrice = 499.99m,
                            Style = "Kids"
                        },
                        new
                        {
                            Id = 14,
                            CommissionPercentage = 13.0m,
                            Manufacturer = "Surly",
                            Name = "Cargo Hauler Max",
                            PurchasePrice = 1400m,
                            QuantityOnHand = 4,
                            SalePrice = 2399.99m,
                            Style = "Cargo"
                        },
                        new
                        {
                            Id = 15,
                            CommissionPercentage = 12.5m,
                            Manufacturer = "Salsa",
                            Name = "Fat Tire Beast",
                            PurchasePrice = 1350m,
                            QuantityOnHand = 6,
                            SalePrice = 2299.99m,
                            Style = "Fat Tire"
                        },
                        new
                        {
                            Id = 16,
                            CommissionPercentage = 14.0m,
                            Manufacturer = "Cannondale",
                            Name = "Road Racer Elite",
                            PurchasePrice = 1800m,
                            QuantityOnHand = 4,
                            SalePrice = 2999.99m,
                            Style = "Road"
                        },
                        new
                        {
                            Id = 17,
                            CommissionPercentage = 11.0m,
                            Manufacturer = "Trek",
                            Name = "Touring Adventure",
                            PurchasePrice = 1200m,
                            QuantityOnHand = 8,
                            SalePrice = 1999.99m,
                            Style = "Touring"
                        },
                        new
                        {
                            Id = 18,
                            CommissionPercentage = 13.5m,
                            Manufacturer = "Specialized",
                            Name = "Electric Cruiser E1",
                            PurchasePrice = 1500m,
                            QuantityOnHand = 7,
                            SalePrice = 2599.99m,
                            Style = "Electric"
                        },
                        new
                        {
                            Id = 19,
                            CommissionPercentage = 7.0m,
                            Manufacturer = "Haro",
                            Name = "BMX Stunt Pro",
                            PurchasePrice = 450m,
                            QuantityOnHand = 18,
                            SalePrice = 799.99m,
                            Style = "BMX"
                        },
                        new
                        {
                            Id = 20,
                            CommissionPercentage = 15.5m,
                            Manufacturer = "Santa Cruz",
                            Name = "Mountain Downhill Expert",
                            PurchasePrice = 1900m,
                            QuantityOnHand = 3,
                            SalePrice = 3299.99m,
                            Style = "Mountain"
                        },
                        new
                        {
                            Id = 21,
                            CommissionPercentage = 16.0m,
                            Manufacturer = "Cervélo",
                            Name = "Triathlon Champion",
                            PurchasePrice = 2200m,
                            QuantityOnHand = 2,
                            SalePrice = 3899.99m,
                            Style = "Triathlon"
                        },
                        new
                        {
                            Id = 22,
                            CommissionPercentage = 7.0m,
                            Manufacturer = "Electra",
                            Name = "Comfort City Plus",
                            PurchasePrice = 550m,
                            QuantityOnHand = 22,
                            SalePrice = 899.99m,
                            Style = "Urban"
                        },
                        new
                        {
                            Id = 23,
                            CommissionPercentage = 8.5m,
                            Manufacturer = "Giant",
                            Name = "Mountain Trail Lite",
                            PurchasePrice = 800m,
                            QuantityOnHand = 13,
                            SalePrice = 1299.99m,
                            Style = "Mountain"
                        },
                        new
                        {
                            Id = 24,
                            CommissionPercentage = 14.0m,
                            Manufacturer = "Trek",
                            Name = "Road Speed RS7",
                            PurchasePrice = 1650m,
                            QuantityOnHand = 5,
                            SalePrice = 2799.99m,
                            Style = "Road"
                        },
                        new
                        {
                            Id = 25,
                            CommissionPercentage = 11.0m,
                            Manufacturer = "Rad Power Bikes",
                            Name = "Electric City Commuter",
                            PurchasePrice = 1100m,
                            QuantityOnHand = 9,
                            SalePrice = 1899.99m,
                            Style = "Electric"
                        });
                });

            modelBuilder.Entity("server.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalespersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalespersonId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionAmount = 157.50m,
                            CustomerId = 1,
                            ProductId = 1,
                            SalePrice = 1499.99m,
                            SalesDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommissionAmount = 264.00m,
                            CustomerId = 2,
                            ProductId = 2,
                            SalePrice = 2199.99m,
                            SalesDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommissionAmount = 110.50m,
                            CustomerId = 3,
                            ProductId = 3,
                            SalePrice = 1299.99m,
                            SalesDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommissionAmount = 126.00m,
                            CustomerId = 4,
                            ProductId = 4,
                            SalePrice = 1399.99m,
                            SalesDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 5,
                            CommissionAmount = 220.00m,
                            CustomerId = 5,
                            ProductId = 5,
                            SalePrice = 1999.99m,
                            SalesDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 2
                        },
                        new
                        {
                            Id = 6,
                            CommissionAmount = 337.50m,
                            CustomerId = 6,
                            ProductId = 6,
                            SalePrice = 2499.99m,
                            SalesDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 3
                        },
                        new
                        {
                            Id = 7,
                            CommissionAmount = 540.00m,
                            CustomerId = 7,
                            ProductId = 7,
                            SalePrice = 3599.99m,
                            SalesDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 4
                        },
                        new
                        {
                            Id = 8,
                            CommissionAmount = 75.00m,
                            CustomerId = 8,
                            ProductId = 8,
                            SalePrice = 999.99m,
                            SalesDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 5
                        },
                        new
                        {
                            Id = 9,
                            CommissionAmount = 96.00m,
                            CustomerId = 9,
                            ProductId = 9,
                            SalePrice = 1199.99m,
                            SalesDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 6
                        },
                        new
                        {
                            Id = 10,
                            CommissionAmount = 218.50m,
                            CustomerId = 10,
                            ProductId = 10,
                            SalePrice = 1899.99m,
                            SalesDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 7
                        },
                        new
                        {
                            Id = 11,
                            CommissionAmount = 160.00m,
                            CustomerId = 11,
                            ProductId = 11,
                            SalePrice = 1599.99m,
                            SalesDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 8
                        },
                        new
                        {
                            Id = 12,
                            CommissionAmount = 287.50m,
                            CustomerId = 12,
                            ProductId = 12,
                            SalePrice = 2299.99m,
                            SalesDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 9
                        },
                        new
                        {
                            Id = 13,
                            CommissionAmount = 30.00m,
                            CustomerId = 13,
                            ProductId = 13,
                            SalePrice = 499.99m,
                            SalesDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 10
                        },
                        new
                        {
                            Id = 14,
                            CommissionAmount = 312.00m,
                            CustomerId = 14,
                            ProductId = 14,
                            SalePrice = 2399.99m,
                            SalesDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 11
                        },
                        new
                        {
                            Id = 15,
                            CommissionAmount = 287.50m,
                            CustomerId = 15,
                            ProductId = 15,
                            SalePrice = 2299.99m,
                            SalesDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 12
                        },
                        new
                        {
                            Id = 16,
                            CommissionAmount = 420.00m,
                            CustomerId = 16,
                            ProductId = 16,
                            SalePrice = 2999.99m,
                            SalesDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 13
                        },
                        new
                        {
                            Id = 17,
                            CommissionAmount = 220.00m,
                            CustomerId = 17,
                            ProductId = 17,
                            SalePrice = 1999.99m,
                            SalesDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 14
                        },
                        new
                        {
                            Id = 18,
                            CommissionAmount = 351.00m,
                            CustomerId = 18,
                            ProductId = 18,
                            SalePrice = 2599.99m,
                            SalesDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 15
                        },
                        new
                        {
                            Id = 19,
                            CommissionAmount = 56.00m,
                            CustomerId = 19,
                            ProductId = 19,
                            SalePrice = 799.99m,
                            SalesDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 20,
                            CommissionAmount = 511.50m,
                            CustomerId = 20,
                            ProductId = 20,
                            SalePrice = 3299.99m,
                            SalesDate = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 2
                        },
                        new
                        {
                            Id = 21,
                            CommissionAmount = 624.00m,
                            CustomerId = 21,
                            ProductId = 21,
                            SalePrice = 3899.99m,
                            SalesDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 3
                        },
                        new
                        {
                            Id = 22,
                            CommissionAmount = 63.00m,
                            CustomerId = 22,
                            ProductId = 22,
                            SalePrice = 899.99m,
                            SalesDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 4
                        },
                        new
                        {
                            Id = 23,
                            CommissionAmount = 110.50m,
                            CustomerId = 23,
                            ProductId = 23,
                            SalePrice = 1299.99m,
                            SalesDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 5
                        },
                        new
                        {
                            Id = 24,
                            CommissionAmount = 392.00m,
                            CustomerId = 24,
                            ProductId = 24,
                            SalePrice = 2799.99m,
                            SalesDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 6
                        },
                        new
                        {
                            Id = 25,
                            CommissionAmount = 209.00m,
                            CustomerId = 25,
                            ProductId = 25,
                            SalePrice = 1899.99m,
                            SalesDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 7
                        },
                        new
                        {
                            Id = 26,
                            CommissionAmount = 157.50m,
                            CustomerId = 26,
                            ProductId = 1,
                            SalePrice = 1499.99m,
                            SalesDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 8
                        },
                        new
                        {
                            Id = 27,
                            CommissionAmount = 264.00m,
                            CustomerId = 27,
                            ProductId = 2,
                            SalePrice = 2199.99m,
                            SalesDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 9
                        },
                        new
                        {
                            Id = 28,
                            CommissionAmount = 110.50m,
                            CustomerId = 28,
                            ProductId = 3,
                            SalePrice = 1299.99m,
                            SalesDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 10
                        },
                        new
                        {
                            Id = 29,
                            CommissionAmount = 126.00m,
                            CustomerId = 29,
                            ProductId = 4,
                            SalePrice = 1399.99m,
                            SalesDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 11
                        },
                        new
                        {
                            Id = 30,
                            CommissionAmount = 220.00m,
                            CustomerId = 30,
                            ProductId = 5,
                            SalePrice = 1999.99m,
                            SalesDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 12
                        },
                        new
                        {
                            Id = 31,
                            CommissionAmount = 337.50m,
                            CustomerId = 1,
                            ProductId = 6,
                            SalePrice = 2499.99m,
                            SalesDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 13
                        },
                        new
                        {
                            Id = 32,
                            CommissionAmount = 540.00m,
                            CustomerId = 2,
                            ProductId = 7,
                            SalePrice = 3599.99m,
                            SalesDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 14
                        },
                        new
                        {
                            Id = 33,
                            CommissionAmount = 75.00m,
                            CustomerId = 3,
                            ProductId = 8,
                            SalePrice = 999.99m,
                            SalesDate = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 15
                        },
                        new
                        {
                            Id = 34,
                            CommissionAmount = 96.00m,
                            CustomerId = 4,
                            ProductId = 9,
                            SalePrice = 1199.99m,
                            SalesDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 35,
                            CommissionAmount = 218.50m,
                            CustomerId = 5,
                            ProductId = 10,
                            SalePrice = 1899.99m,
                            SalesDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 2
                        },
                        new
                        {
                            Id = 36,
                            CommissionAmount = 160.00m,
                            CustomerId = 6,
                            ProductId = 11,
                            SalePrice = 1599.99m,
                            SalesDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 3
                        },
                        new
                        {
                            Id = 37,
                            CommissionAmount = 287.50m,
                            CustomerId = 7,
                            ProductId = 12,
                            SalePrice = 2299.99m,
                            SalesDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 4
                        },
                        new
                        {
                            Id = 38,
                            CommissionAmount = 30.00m,
                            CustomerId = 8,
                            ProductId = 13,
                            SalePrice = 499.99m,
                            SalesDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 5
                        },
                        new
                        {
                            Id = 39,
                            CommissionAmount = 312.00m,
                            CustomerId = 9,
                            ProductId = 14,
                            SalePrice = 2399.99m,
                            SalesDate = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 6
                        },
                        new
                        {
                            Id = 40,
                            CommissionAmount = 287.50m,
                            CustomerId = 10,
                            ProductId = 15,
                            SalePrice = 2299.99m,
                            SalesDate = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 7
                        },
                        new
                        {
                            Id = 41,
                            CommissionAmount = 420.00m,
                            CustomerId = 11,
                            ProductId = 16,
                            SalePrice = 2999.99m,
                            SalesDate = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 8
                        },
                        new
                        {
                            Id = 42,
                            CommissionAmount = 220.00m,
                            CustomerId = 12,
                            ProductId = 17,
                            SalePrice = 1999.99m,
                            SalesDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 9
                        },
                        new
                        {
                            Id = 43,
                            CommissionAmount = 351.00m,
                            CustomerId = 13,
                            ProductId = 18,
                            SalePrice = 2599.99m,
                            SalesDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 10
                        },
                        new
                        {
                            Id = 44,
                            CommissionAmount = 56.00m,
                            CustomerId = 14,
                            ProductId = 19,
                            SalePrice = 799.99m,
                            SalesDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 11
                        },
                        new
                        {
                            Id = 45,
                            CommissionAmount = 511.50m,
                            CustomerId = 15,
                            ProductId = 20,
                            SalePrice = 3299.99m,
                            SalesDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 12
                        },
                        new
                        {
                            Id = 46,
                            CommissionAmount = 624.00m,
                            CustomerId = 16,
                            ProductId = 21,
                            SalePrice = 3899.99m,
                            SalesDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 13
                        },
                        new
                        {
                            Id = 47,
                            CommissionAmount = 63.00m,
                            CustomerId = 17,
                            ProductId = 22,
                            SalePrice = 899.99m,
                            SalesDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 14
                        },
                        new
                        {
                            Id = 48,
                            CommissionAmount = 110.50m,
                            CustomerId = 18,
                            ProductId = 23,
                            SalePrice = 1299.99m,
                            SalesDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 15
                        },
                        new
                        {
                            Id = 49,
                            CommissionAmount = 392.00m,
                            CustomerId = 19,
                            ProductId = 24,
                            SalePrice = 2799.99m,
                            SalesDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 1
                        },
                        new
                        {
                            Id = 50,
                            CommissionAmount = 209.00m,
                            CustomerId = 20,
                            ProductId = 25,
                            SalePrice = 1899.99m,
                            SalesDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalespersonId = 2
                        });
                });

            modelBuilder.Entity("server.Models.Salesperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manager")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Salespersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Seattle, WA 98101",
                            FirstName = "John",
                            LastName = "Smith",
                            Manager = "Emily Brown",
                            Phone = "206-555-1234",
                            StartDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave, Seattle, WA 98102",
                            FirstName = "Sarah",
                            LastName = "Johnson",
                            Manager = "Emily Brown",
                            Phone = "206-555-2345",
                            StartDate = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St, Seattle, WA 98103",
                            FirstName = "Michael",
                            LastName = "Davis",
                            Manager = "Emily Brown",
                            Phone = "206-555-3456",
                            StartDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Cedar Rd, Seattle, WA 98104",
                            FirstName = "Jessica",
                            LastName = "Wilson",
                            Manager = "Emily Brown",
                            Phone = "206-555-4567",
                            StartDate = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Birch Ave, Seattle, WA 98105",
                            FirstName = "David",
                            LastName = "Martinez",
                            Manager = "Emily Brown",
                            Phone = "206-555-5678",
                            StartDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Walnut St, Seattle, WA 98106",
                            FirstName = "Emily",
                            LastName = "Taylor",
                            Manager = "Marcus Johnson",
                            Phone = "206-555-6789",
                            StartDate = new DateTime(2020, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "147 Spruce Dr, Seattle, WA 98107",
                            FirstName = "James",
                            LastName = "Anderson",
                            Manager = "Marcus Johnson",
                            Phone = "206-555-7890",
                            StartDate = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "258 Maple Ln, Seattle, WA 98108",
                            FirstName = "Amanda",
                            LastName = "Thomas",
                            Manager = "Marcus Johnson",
                            Phone = "206-555-8901",
                            StartDate = new DateTime(2022, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "369 Elm Pl, Seattle, WA 98109",
                            FirstName = "Daniel",
                            LastName = "Rodriguez",
                            Manager = "Marcus Johnson",
                            Phone = "206-555-9012",
                            StartDate = new DateTime(2021, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "741 Oak Ct, Seattle, WA 98110",
                            FirstName = "Ashley",
                            LastName = "Garcia",
                            Manager = "Marcus Johnson",
                            Phone = "206-555-0123",
                            StartDate = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Address = "852 Cedar Pl, Seattle, WA 98111",
                            FirstName = "Robert",
                            LastName = "Martinez",
                            Manager = "Sophia Reynolds",
                            Phone = "206-555-1234",
                            StartDate = new DateTime(2018, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Address = "963 Pine Rd, Seattle, WA 98112",
                            FirstName = "Jennifer",
                            LastName = "Brown",
                            Manager = "Sophia Reynolds",
                            Phone = "206-555-2345",
                            StartDate = new DateTime(2019, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Address = "159 Birch Dr, Seattle, WA 98113",
                            FirstName = "Christopher",
                            LastName = "Lee",
                            Manager = "Sophia Reynolds",
                            Phone = "206-555-3456",
                            StartDate = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Address = "357 Walnut Ave, Seattle, WA 98114",
                            FirstName = "Elizabeth",
                            LastName = "Harris",
                            Manager = "Sophia Reynolds",
                            Phone = "206-555-4567",
                            StartDate = new DateTime(2021, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Address = "258 Spruce St, Seattle, WA 98115",
                            FirstName = "Matthew",
                            LastName = "Clark",
                            Manager = "Sophia Reynolds",
                            Phone = "206-555-5678",
                            StartDate = new DateTime(2020, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Address = "753 Maple Ave, Seattle, WA 98116",
                            FirstName = "Lauren",
                            LastName = "Lewis",
                            Manager = "William Phillips",
                            Phone = "206-555-6789",
                            StartDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TerminationDate = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Address = "951 Elm St, Seattle, WA 98117",
                            FirstName = "Kevin",
                            LastName = "Walker",
                            Manager = "William Phillips",
                            Phone = "206-555-7890",
                            StartDate = new DateTime(2019, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Address = "357 Oak Rd, Seattle, WA 98118",
                            FirstName = "Michelle",
                            LastName = "Young",
                            Manager = "William Phillips",
                            Phone = "206-555-8901",
                            StartDate = new DateTime(2021, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Address = "864 Cedar St, Seattle, WA 98119",
                            FirstName = "Jason",
                            LastName = "Allen",
                            Manager = "William Phillips",
                            Phone = "206-555-9012",
                            StartDate = new DateTime(2018, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TerminationDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Address = "159 Pine Dr, Seattle, WA 98120",
                            FirstName = "Kimberly",
                            LastName = "Scott",
                            Manager = "William Phillips",
                            Phone = "206-555-0123",
                            StartDate = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("server.Models.Discount", b =>
                {
                    b.HasOne("server.Models.Product", "Product")
                        .WithMany("Discounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("server.Models.Sale", b =>
                {
                    b.HasOne("server.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Salesperson", "Salesperson")
                        .WithMany("Sales")
                        .HasForeignKey("SalespersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Salesperson");
                });

            modelBuilder.Entity("server.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("server.Models.Product", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("server.Models.Salesperson", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
